version: '3'

services:
  fastapi:
    build: fastapi/
    ports: 
      - 8000:8000
    volumes:
      - ./airflow/clean_data:/airflow/clean_data
      - ./airflow/clean_model:/airflow/clean_model
      - ./data:/data
      - ./fastapi:/fastapi
    networks:
      - deploy_network
    container_name: fastapi

  streamlit:
    build: streamlit/
    depends_on:
      - fastapi
    ports: 
        - 8501:8501
    volumes:
      - ./airflow/clean_data:/airflow/clean_data
      - ./airflow/clean_model:/airflow/clean_model
      - ./data:/data
      - ./streamlit:/streamlit
    networks:
      - deploy_network
    container_name: streamlit

networks:
  deploy_network:
    driver: bridge